services:
  postgres:
    image: postgres:latest
    container_name: go-tasks-postgres
    environment:
      POSTGRES_USER: someuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: gorm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: go-tasks-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local